# GitHub Actions workflow for deploying both frontend (Angular) and backend (.NET) to Azure App Service

name: Deploy Shopping Cart App to Azure

on:
  push:
    branches:
      - main

jobs:
  # build-and-deploy-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '9.0.x'

  #     - name: Restore dependencies
  #       run: dotnet restore ./backend/backend.csproj

  #     - name: Build
  #       run: dotnet build ./backend/backend.csproj --configuration Release --no-restore

  #     - name: Publish
  #       run: dotnet publish ./backend/backend.csproj --configuration Release --output ./publish

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: ${{ secrets.AZURE_BACKEND_APP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
  #         package: ./publish

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci --prefix frontend

      - name: Build Angular app
        run: npm run build --prefix frontend

      # - name: Copy nginx.conf to dist/frontend/
      #   run: cp frontend/src/nginx.conf frontend/dist/frontend/nginx.conf

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: bestshopping
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: frontend/dist/frontend
