# GitHub Actions workflow to deploy Azure resources using Bicep
name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        uses: azure/bicep-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-shopping-cart
          bicepFilePath: infra/main.bicep
          parametersFilePath: infra/main.bicepparam
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
