# GitHub Actions workflow to deploy Azure resources using Bicep
name: Deploy Azure Infrastructure

on:
  workflow_dispatch:  

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert .bicepparam to JSON
        run: |
          az bicep build-params --file infra/main.bicepparam --outfile infra/main.parameters.json

      - name: Deploy Bicep template
        uses: azure/cli@v2
        with:
          azcliversion: 2.56.0
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az deployment group create --resource-group rg-shopping-cart --template-file infra/main.bicep --parameters @infra/main.parameters.json
