# GitHub Actions workflow to deploy Azure resources using Bicep

name: Deploy Azure Infrastructure

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:  

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert .bicepparam to JSON
        run: |
          az bicep build-params --file infra/main.bicepparam --outfile infra/main.parameters.json

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        uses: azure/bicep-deploy@v2
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: rg-shopping-cart
          template-file: infra/main.bicep
          parameters-file: infra/main.bicepparam
          scope: resourceGroup
